### DISCUSSION TITLE
A few questions about analyzing Rust-derived LLVM

### DISCUSSION THREAD

**Discussion by nano-o** [seahorn/seahorn#482] [General]
Hello,
I'm trying to analyze the file [assembly.ll](https://github.com/nano-o/soroban-seahorn/blob/f3c082e667d2b7af159bd521d14aaa17cd9b24a0/nostd-test-contract/assembly.ll), which is generated by rustc from [this Rust program](https://github.com/nano-o/soroban-seahorn/blob/f3c082e667d2b7af159bd521d14aaa17cd9b24a0/nostd-test-contract/src/main.rs).
My goal is to run a bit-precise analysis and obtain counter-examples.
The problem is that seahorn says `unsat` although running the executable ends with `[sea] __VERIFIER_error was executed`.

I'm using `sea_base.yaml` from `verify-c-common` where I commented out `externalize-addr-taken-functions` (since it seems that important functionality in the code relies on such functions).

I see a few warnings starting with `Warning: not lowering an initializer for a global struct:`  and
```
Warning: unhandled instruction:   %bcmp.i.i.i.i = call i32 @bcmp(i8* noundef nonnull dereferenceable(9) %_7, i8* noun
def nonnull dereferenceable(9) %_9, i64 9) #15, !alias.scope !72, !noalias !79 @ bb2.i.i.i221.i.critedge in main
```
If I link to a handwritten implementation of `bcmp` to obtain [this bitcode](https://github.com/nano-o/soroban-seahorn/blob/2bddc75601eb1843d6eaed7bb10b03e11fa7aa16/nostd-test-contract/assembly_bcmp_impl.ll) I then get an error:
```
Error: unhandled call instruction:   %bcmp.i.i.i.i = call i32 @bcmp(i8* nonnull dereferenceable(9) %_7, i8* nonnull d
ereferenceable(9) %_9, i64 9) #15, !alias.scope !76, !noalias !80
#0 0x000055b72857c691 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/home/user/seahorn/build/run/bin/seahorn+0
x36da691)
#1 0x000055b72857a53c llvm::sys::RunSignalHandlers() (/home/user/seahorn/build/run/bin/seahorn+0x36d853c)
#2 0x000055b72857cbb6 SignalHandler(int) sat_proof_trim.cpp:0:0
#3 0x00007fc649509520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
#4 0x000055b726069c92 (/home/user/seahorn/build/run/bin/seahorn+0x11c7c92)
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.      Program arguments: /home/user/seahorn/build/run/bin/seahorn --horn-bmc --horn-bv2 --log=opsem --lower-gv-init
-struct=false --horn-shadow-mem-alloc-is-def --keep-shadows=true --sea-dsa=cs --sea-dsa-type-aware --horn-solve -horn
-inter-proc -horn-sem-lvl=mem --horn-step=large /tmp/verify-c-common/bitcode_bcmp_impl.pp.ms.o.ul.cut.o.bc --horn-uni
fy-assumes=true --horn-gsa --horn-vcgen-use-ite --horn-vcgen-only-dataflow=true --horn-bmc-coi=true --sea-opsem-alloc
ator=static --horn-explicit-sp0=false --horn-bv2-lambdas --horn-bv2-simplify=true --horn-bv2-extra-widemem --horn-sta
ts=true
1.      Running pass 'BmcPass' on module '/tmp/verify-c-common/bitcode_bcmp_impl.pp.ms.o.ul.cut.o.bc'.
make: *** [Makefile:65: verify-yama-bcmp-impl] Error 251
```

Any suggestion on where to start approaching this problem?

I'd like to start with analyzing simpler code, but this seems to be the most trivial example I could get in my application domain. It is a smart contract that just increments an integer. However I couldn't get rustc to emit less than those ~6000 lines of LLVM assembly.

**Comment by agurfinkel** [comment]
We have tried analyzing complete Rust executable in the past. This is not easy because Rust includes a large runtime library at the beginning of the code. Our first solution to that was to extract the entry point from the generated bitcode. The current state of this project is here: https://github.com/priyasiddharth/seaurchin

Since Rust is a quickly moving target, I am expecting the repo to become stale pretty quickly. Still, you might be able to get it going fairly quickly since most of it is Rust code that rewrites the target llvm file.

More recently, we are experimenting with using LTO route. We start with our own entrypoint in C, link Rust library, and use LTO to generate bitcode. This project is here: https://github.com/GuyBlumenthal/c-rust/tree/verify-script . At the very least we are able to verify a tiny program that adds two numbers pretty quickly :)

The current bottlenecks are in requiring to link the complete rust std library. This adds a lot of code that is then removed by COI -- but this takes time. We are working on linking only parts of std lib, and writing seahorn-specific version of core components, such as Vec.

As to your issue. If `@bcmp` is not linked, it will be treated as non-deterministic. Initializers for some very large structures might be ignored. If functions whose address is taken are not externalized, the inlining will not work properly. Many other things are possible. At any rate there should not be segfaults. I'm happy to debug those if you can tell me how to reproduce.

**Reply by nano-o** [reply]
Thanks for the response! I am using the LTO approach with `no_std` (so I'm not linking with the standard library, only with the `alloc` library in `core`) and my own C-like entry point (although I didn't know of the project you linked to).

I think you can reproduce by running `sea yama -y sea_base.yaml bpf` on this LLVM 14 file:
https://github.com/nano-o/soroban-seahorn/blob/2bddc75601eb1843d6eaed7bb10b03e11fa7aa16/nostd-test-contract/assembly_bcmp_impl.ll

Are you saying that I must externalize functions whose address is taken? Does that mean they will be treated as non-deterministic?

Does the "not lowering" warning means the initializer is completely ignored?

**Comment by agurfinkel** [comment]
I get `sat` on your example in both `debug` and `build` mode. No crashes. I'm running a slightly different branch locally, but it should not make a difference. Are you on the latest `dev14`? 

Some observations:

Use `--horn-explicit-sp0=true`. This makes base of stack pointer a fixed number. In your benchmark this makes a significant difference to the simplifier. This is something I'm working on, but for now, enabling explicit stack pointer is a good way forward.

Global initializers are lowered to code for the purpose of alias analysis that does not understand global initializers by itself.
So the obvious issue are tables of function pointers (like vtables). There is some support for them, but this is a weak spot for our alias analysis. If this is needed and you have a smallish example, I can see what can be done. 

In the current code, I see some vtables but they seem to be for debug and fmt functions, so probably they do not matter.

In BMC engine itself, global initializers are converted into byte maps (i.e., evaluated) and are converted to symbolic representation. Since this can be unnecessarily large, there is a command line flag that limits the size of global that is initialized: [here](https://github.com/seahorn/seahorn/blob/dev14/lib/seahorn/BvOpSem2.cc#L145).

Externalizing address-taken functions is done after devirtualization. If an address of `foo()` is taken, then a new function with the name `foo.addr()` is created, and address of `foo.addr` is used instead of `foo`. This allows LLVM to inline `foo`. Since devirtualization table uses function addresses to decide which function to call, it is not affected. 

I do see warnings about indirect function calls that get to the bmc engine. Such as `Warning: unhandled instruction:   %_243 = call { i64, i64 } %_241...`

If this is something that can be easily minimized, it will help narrowing this down.

**Reply by nano-o** [reply]
It looks like I am using the latest `dev14` but I still get the crash. What do you mean by `debug` and `build` mode?

```
user@0a33229e5aa2:~/nostd-test-contract$ seahorn --version
Ubuntu LLVM version 14.0.0
  
  Optimized build.
  Default target: x86_64-pc-linux-gnu
  Host CPU: alderlake

SeaHorn (http://seahorn.github.io/):
  SeaHorn version 14.0.0-rc0-7f87bb34
```
Full output:
```
user@0a33229e5aa2:~/nostd-test-contract$ sea yama -y /home/user/verify-c-common/seahorn/sea_base.yaml bpf test.ll 
Yama executing command:
/home/user/seahorn/build/run/bin/sea bpf -O3 --inline --enable-loop-idiom --enable-indvar --no-lower-gv-init-struct -
-externalize-addr-taken-functions --no-kill-vaarg --with-arith-overflow=true --horn-unify-assumes=true --horn-gsa --n
o-fat-fns=bcmp,memcpy,assert_bytes_match,ensure_linked_list_is_allocated,sea_aws_linked_list_is_valid --dsa=sea-cs-t 
--devirt-functions=sea-dsa --bmc=opsem --horn-vcgen-use-ite --horn-vcgen-only-dataflow=true --horn-bmc-coi=true --sea
-opsem-allocator=static --horn-explicit-sp0=true --horn-bv2-lambdas --horn-bv2-simplify=true --horn-bv2-extra-widemem
 -S --keep-temps --temp-dir=/tmp/verify-c-common --horn-stats=true test.ll
/home/user/seahorn/build/run/bin/seapp -o /tmp/verify-c-common/test.pp.bc -S --simplifycfg-sink-common=false --horn-i
nline-all --strip-extern=false --promote-assumptions=false --lower-gv-init-struct=false --devirt-functions --devirt-f
unctions-method=sea-dsa --externalize-addr-taken-funcs --kill-vaarg=false --ignore-def-verifier-fn=false --horn-keep-
arith-overflow=true test.ll
Warning: Externalizing function: _ZN4core3ptr136drop_in_place$LT$soroban_sdk..env..Env..register_contract..InternalCo
ntractFunctionSet$LT$nostd_test_contract..IncrementContract$GT$$GT$17h66e19257b162cc3dE

Warning: Externalizing function: _ZN81_$LT$soroban_env_common..raw_val..ConversionError$u20$as$u20$core..fmt..Debug$G
T$3fmt17h09645f50c7dd57baE

Warning: Externalizing function: _ZN60_$LT$core..cell..BorrowError$u20$as$u20$core..fmt..Debug$GT$3fmt17hf1f885c7c500
7e94E

Warning: Externalizing function: _ZN150_$LT$soroban_sdk..env..Env..register_contract..InternalContractFunctionSet$LT$
T$GT$$u20$as$u20$soroban_env_verification..host..ContractFunctionSet$GT$4call17hb0c7fb317ba9eab8E

Warning: Externalizing function: _ZN63_$LT$core..cell..BorrowMutError$u20$as$u20$core..fmt..Debug$GT$3fmt17h9ceba537f
036ff97E

Warning: not lowering an initializer for a global struct:  vtable.0
Warning: not lowering an initializer for a global struct:  alloc210
Warning: not lowering an initializer for a global struct:  vtable.2
Warning: not lowering an initializer for a global struct:  alloc215
Warning: not lowering an initializer for a global struct:  alloc433
Warning: not lowering an initializer for a global struct:  alloc948
Warning: not lowering an initializer for a global struct:  alloc951
Warning: not lowering an initializer for a global struct:  vtable.1.142
Warning: not lowering an initializer for a global struct:  vtable.2.143
Warning: not lowering an initializer for a global struct:  alloc1342
Warning: not lowering an initializer for a global struct:  alloc1318
/home/user/seahorn/build/run/bin/seapp --simplifycfg-sink-common=false -o /tmp/verify-c-common/test.pp.ms.bc --horn-m
ixed-sem --ms-reduce-main -S /tmp/verify-c-common/test.pp.bc
/home/user/seahorn/build/run/bin/seaopt -f --simplifycfg-sink-common=false -o /tmp/verify-c-common/test.pp.ms.o.bc -O
3 --unroll-threshold=150 --unroll-allow-partial=false --unroll-partial-threshold=0 --vectorize-slp=false /tmp/verify-
c-common/test.pp.ms.bc -S
/home/user/seahorn/build/run/bin/seaopt -f -o /tmp/verify-c-common/test.pp.ms.o.ul.bc -loop-simplify -fake-latch-exit
 -sea-loop-unroll /tmp/verify-c-common/test.pp.ms.o.bc -S
/home/user/seahorn/build/run/bin/seapp -o /tmp/verify-c-common/test.pp.ms.o.ul.cut.bc --horn-cut-loops -S --back-edge
-cutter-with-asserts=false /tmp/verify-c-common/test.pp.ms.o.ul.bc
Warning: found 4 possible reads of undefined values
/home/user/seahorn/build/run/bin/seaopt -f --simplifycfg-sink-common=false -o /tmp/verify-c-common/test.pp.ms.o.ul.cu
t.o.bc -O3 --unroll-threshold=150 --unroll-allow-partial=false --unroll-partial-threshold=0 --vectorize-slp=false /tm
p/verify-c-common/test.pp.ms.o.ul.cut.bc -S
/home/user/seahorn/build/run/bin/seahorn --horn-bmc --horn-bv2 --log=opsem --lower-gv-init-struct=false --horn-shadow
-mem-alloc-is-def --keep-shadows=true --sea-dsa=cs --sea-dsa-type-aware --horn-solve -horn-inter-proc -horn-sem-lvl=m
em --horn-step=large /tmp/verify-c-common/test.pp.ms.o.ul.cut.o.bc --horn-unify-assumes=true --horn-gsa --horn-vcgen-
use-ite --horn-vcgen-only-dataflow=true --horn-bmc-coi=true --sea-opsem-allocator=static --horn-explicit-sp0=true --h
orn-bv2-lambdas --horn-bv2-simplify=true --horn-bv2-extra-widemem --horn-stats=true
Warning: not lowering an initializer for a global struct:  alloc215
Sea-Dsa type aware!
Omnipotent char: omni_i8*
Info: pointer size: 8, word size: 8
Info: Trackable memory is not present
Functions: 
NONE
Globals: 
0x00000008048000 @alloc215
!3 Alloca of 40 bytes:   %_6.i.i.i205.i = alloca %"core::result::Result<stellar_xdr::next::generated::ScVal, raw_val:
:ConversionError>", align 8, !sea.dsa.allocsite !10
!3 Alloca of 10 bytes:   %_8.i.i.i = alloca %"soroban_env_common::symbol::SymbolStr", align 1, !sea.dsa.allocsite !12
Error: unhandled call instruction:   %bcmp.i.i.i.i = call i32 @bcmp(i8* nonnull dereferenceable(9) %_7, i8* nonnull d
ereferenceable(9) %_9, i64 9) #15, !alias.scope !76, !noalias !80
#0 0x000055e4357ce861 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/home/user/seahorn/build/run/bin/seahorn+0
x36e6861)
#1 0x000055e4357cc70c llvm::sys::RunSignalHandlers() (/home/user/seahorn/build/run/bin/seahorn+0x36e470c)
#2 0x000055e4357ced86 SignalHandler(int) sat_proof_trim.cpp:0:0
#3 0x00007fccf4dd0520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
#4 0x000055e4332b6ef2 (/home/user/seahorn/build/run/bin/seahorn+0x11ceef2)
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.      Program arguments: /home/user/seahorn/build/run/bin/seahorn --horn-bmc --horn-bv2 --log=opsem --lower-gv-init
-struct=false --horn-shadow-mem-alloc-is-def --keep-shadows=true --sea-dsa=cs --sea-dsa-type-aware --horn-solve -horn
-inter-proc -horn-sem-lvl=mem --horn-step=large /tmp/verify-c-common/test.pp.ms.o.ul.cut.o.bc --horn-unify-assumes=tr
ue --horn-gsa --horn-vcgen-use-ite --horn-vcgen-only-dataflow=true --horn-bmc-coi=true --sea-opsem-allocator=static -
-horn-explicit-sp0=true --horn-bv2-lambdas --horn-bv2-simplify=true --horn-bv2-extra-widemem --horn-stats=true
1.      Running pass 'BmcPass' on module '/tmp/verify-c-common/test.pp.ms.o.ul.cut.o.bc'.
```
Contents of yaml file:
```
verify_options:
# Optimization level
  '-O3': ''
# 
# PREPROCESSING
#
  inline: ''
  enable-loop-idiom: ''
  enable-indvar: ''
  no-lower-gv-init-struct: ''
  externalize-addr-taken-functions: ''
  no-kill-vaarg: ''
  with-arith-overflow: true
  horn-unify-assumes: true
  horn-gsa: ''
# do not instrument library functions with memory assertions 
  no-fat-fns: 'bcmp,memcpy,assert_bytes_match,ensure_linked_list_is_allocated,sea_aws_linked_list_is_valid'
# context-sensitive type-aware alias analysis 
  dsa: sea-cs-t
# weak support for function pointers. sea-dsa is better that types but less stable
  devirt-functions: 'sea-dsa'
# bit-precise memory-precise operational semantics
  bmc: opsem
  horn-vcgen-use-ite: ''
# ignore control flow
  horn-vcgen-only-dataflow: true
# reduce by data dependence
  horn-bmc-coi: true
# static allocator supports symbolic allocation size
  sea-opsem-allocator: static
# stack allocation from a symbolic starting point
  horn-explicit-sp0: true
# lambdas for memory
  horn-bv2-lambdas: ''
# use z3 simplifier during vcgen
  horn-bv2-simplify: true
# wide memory manager to track pointer sizes
  horn-bv2-extra-widemem: ''
# intermediate results in human readable form for debugging
  '-S': ''
# keep intermediate results for debugging 
  keep-temps: ''
  temp-dir: /tmp/verify-c-common
# time and result stats
  horn-stats: true
```

**Comment by agurfinkel** [comment]
The root cause of the crash is a bad error handling for the unexpected call instruction. I will fix the error message to be more user friendly. 

Not sure why the call is not resolved. I've noticed that in my config, I've type-based virtual call resolution. That  is:
```
devirt-functions: 'types'
```
I still need to check why devirt with `sea-dsa` leaves virtual calls unresolved...

**Comment by agurfinkel** [comment]
A little further digging:

`bcmp` is compiled with optimization and inlining disabled. This prevents it from being marked internal and inlined. 
If it is compiled with clang, use `-O1 -Xclang -disable-llvm-optzns` instead of `-O0`. This does not run optimizations, but still enables optimizations to occur later in the pipeline (i.e., in seahorn).

I've tried to manually change the attributes of `bcmp`, but was not successful. One other issue that I'm seeing is that its calling convention is different than other functions. Something is preventing `bcmp` from being marked `internal` using LLVM's `lib/Transforms/IPO/Internalize.cpp` pass. Since `bcmp` is not marked `internal`, it cannot be marked `alwaysinlined`, and, therefore, cannot be inlined.

**Reply by nano-o** [reply]
It seems that adding `--internalize` to the `llvm-link` call when linking the C implementation of `bcmp` improves the situation. Now there's no error anymore with `devirt-functions: 'sea-dsa'` but it still says `unsat` when actually running the executable results in `[sea] __VERIFIER_error was executed`.

Here's the bitcode file: https://github.com/nano-o/soroban-seahorn/blob/50c4c98712785d70d05780998750c2dceb59e1f4/nostd-test-contract/assembly_bcmp_impl.ll

**Comment by agurfinkel** [comment]
The default unroll bound of 5 (plus some heuristics) is not good enough for this example. I get `sat` with `--bound=10`

Let us know whether this is what is expected or not.

**Reply by nano-o** [reply]
Thanks, that works as expected!

I tried to introduce a symbolic input to see if I could get a counterexample with a sensible value for the symbolic variable and it seems to work too. However I get warnings like `Warning: Failed to get register for:   %_98 = icmp ult i8 %_97, 2` (many of those) and `Warning: unsupported array term extract-value(main@%sm155, 0)_0`. The bitcode file is [here](https://github.com/nano-o/soroban-seahorn/blob/ed44374928a951a2eff33851a2265f9b0dfe70d7/nostd-test-contract/assembly_bcmp_impl.ll) and Rust source [here](https://github.com/nano-o/soroban-seahorn/blob/ed44374928a951a2eff33851a2265f9b0dfe70d7/nostd-test-contract/src/main.rs).

Here's the YAML config I'm using. Does that look sensible? (`horn-vcgen-only-dataflow` sounds like it would lose precision so I set it to false) 
```
verify_options:
# Optimization lelel. Lower to O1 for clearer counterexamples
  '-O1': ''
# 
# PREPROCESSING
#
  inline: ''
  enable-loop-idiom: ''
  enable-indvar: ''
  no-lower-gv-init-struct: ''
  externalize-addr-taken-functions: ''
  no-kill-vaarg: ''
  with-arith-overflow: true
  horn-unify-assumes: true
# do not instrument library functions with memory assertions
  no-fat-fns: 'bcmp,memcpy,assert_bytes_match,ensure_linked_list_is_allocated,sea_aws_linked_list_is_valid'
  horn-gsa: false
# context-sensitive type-aware alias analysis 
  dsa: sea-cs-t
# weak support for function pointers. sea-dsa is better but less stable
  devirt-functions: 'sea-dsa'
# bit-precise memory-precise operational semantics
  bmc: opsem
  horn-vcgen-use-ite: ''
# ignore control flow
  horn-vcgen-only-dataflow: false
# reduce by data dependence
  horn-bmc-coi: true
# static allocator supports symbolic allocation size
  sea-opsem-allocator: static
# stack allocation from a symbolic starting point
  horn-explicit-sp0: true
# lambdas for memory
  horn-bv2-lambdas: false
# use z3 simplifier during vcgen
  horn-bv2-simplify: true
# wide memory manager to track pointer sizes
  horn-bv2-extra-widemem: ''
# intermediate results in human readable form for debugging
  '-S': ''
# keep intermediate results for debugging 
  keep-temps: ''
  temp-dir: /tmp/verify-c-common
# time and result stats
  horn-stats: true
# produce counterexample harness
  cex: /tmp/h.ll
# printable counterexample log
  log: cex
# number of words to unroll symbolic memcpy for array-based memory representation
# should be at least MAX_BUFFER_SIZE
  horn-array-sym-memcpy-unroll-count: 10
# print memory state as a table
# XXX still flaky, sometimes only the last byte can be trusted
  horn-bmc-hexdump: true
  bound: 10
```

**Reply by agurfinkel** [reply]
"dataflow only" option does not loose precision. It simply avoids generating CFG constraints that are redundant. It has positive effect on performance but makes cexs harder to reconstruct. That is why we have different yaml config for cexs. 

The warning usually means that CPI removed too much code and a register Def was removed. I will have to see whether it is your combination of options or our bug that is causing that. 

The last error I do not recognize. When does it happen? I will attempt to repro and tell you how it goes.

**Reply by nano-o** [reply]
I get those warnings when running `sea yama -y /home/user/verify-c-common/seahorn/sea_cex_base.yaml bpf bitcode_bcmp_impl.bc` where `sea_cex_base.yaml` is like above.

**Comment by agurfinkel** [comment]
The combination of flags that you are using is inconsistent. Unfortunately, we do not detect this and do not provide a nice error message to explain. Something to work on...

`horn-gsa` is prereq for `horn-vcgen-only-dataflow` that is a prereq for `horn-bmc-coi`. 
This is not strictly true, rather if you don't have these options as above, you get various forms of abstraction. They are useful in themselves, which why the options allow for them, but definitely confusing for anyone but us :)

With your current set of options some code is taken out of cone of influence, and, you get the error message that a register is not found.

Unfortunately, when COI is disabled, there is a function call that is not inlined that causes seahorn to exit with the same error as when `bcmp` was not found. The problematic function is `_ZN4core3ptr56drop_in_place$LT$stellar_xdr..next..generated..ScVal$GT$17h044a29ff334c2310E"(%"core::result::Result<stellar_xdr::next::generated::ScVal, raw_val::ConversionError>`. The body of the function is included, but for some reason it is not inlined. Seahorn does not like functions that are defined in the compilation unit but are not inlined.

**Comment by agurfinkel** [comment]
The function is not inlined because it is recursive. Is that expected?

**Reply by nano-o** [reply]
I'm looking into it. This seems to be part of serialization code that's automatically generated from XDR specifications. I presume this can't easily be unrolled like with loops. Or can it?

**Reply by nano-o** [reply]
So it looks like this is a destructor generated by the Rust compiler.

**Comment by agurfinkel** [comment]
Strange that automatically generated code would include recursion. Is the recursion depth known? Stack space is limited and architecture dependent, so strange to see recursion in compiler-generated code.

What we plan to do for now is detect such functions and model them non-deterministically. This should work for this case.

Recursion can be unrolled, just like loops, it is just something that we haven't had to do as of yet. We are using LLVM's inliner. It has some support for unrolling recursion, but it is not something compiler likes doing. 

Since we never expect to see recursion in low-level code, we were always hesitant to add support.

**Reply by nano-o** [reply]
That seems to confirm that some destructors generated by Rust are recursive: https://github.com/rust-lang/rust/issues/58068

**Comment by agurfinkel** [comment]
so it seems. This was the exact reason why I thought nobody would do this :)

For now, we can work around this specific set of functions...

**Comment by agurfinkel** [comment]
`_ZN74_$LT$stellar_xdr..next..generated..ScVal$u20$as$u20$core..clone..Clone$GT$5clone17he405b7f8dc390159E.246` this one is also recursive

**Reply by nano-o** [reply]
That one might be harder to avoid. `ScVal` is a recursive structure by design and this looks like a compiler-generated function to clone it.

**Reply by agurfinkel** [reply]
Can't you provide a different non-recursive implementation instead of using `#derive[Clone]`.

In general, I'd expect that in Rust there should always be possible to replace compiler generated code by custom code, by not using derive and providing the appropriate trate implementation.

For now, I'm adding hacks to ignore these functions (instead of aborting). This seems to work on your example.

**Reply by nano-o** [reply]
I could provide a non-recursive implementation of clone but it would be a temporary hack. For something more stable I would need to modify the XDR generator. I'm wondering if it's not easier to add an unrolling pass to seahorn. Could be an exercise for me to get more familiar with LLVM. Does that sound doable as a kind of first exercise?

**Reply by agurfinkel** [reply]
For function inlining, we use the standard LLVM inliner. It has a cost model that avoids recursive functions. However, as far as I can tell, inlining recursive functions is supported. Inlining non-mutually recursive functions should be simple. This can be added as a separate path. Inlining mutually recursive functions might be more challenging. Is it needed here?

Inliner related code in LLVM is here: https://github.com/llvm/llvm-project/tree/release/14.x/llvm/lib/Transforms/IPO 
Look for files with "inline" in them. We use AlwaysInliner by default.

**Reply by nano-o** [reply]
I expect there's mutual recursion involved, e.g. `ScVal` contains `ScVec` contains `ScVal`, but in that particular bitcode file I don't seen any call to a clone function for `ScVec`.

**Comment by agurfinkel** [comment]
Please try latest `dev14`. Should be working now.

**Reply by nano-o** [reply]
Okay I don't get those warnings about registers anymore. I still get `Warning: unsupported array term extract-value(main@%sm155, 0)_0`

Here's the config I'm using now:
```
verify_options:
# Optimization lelel. Lower to O1 for clearer counterexamples
  '-O1': ''
# 
# PREPROCESSING
#
  inline: ''
  enable-loop-idiom: ''
  enable-indvar: ''
  no-lower-gv-init-struct: ''
  externalize-addr-taken-functions: ''
  no-kill-vaarg: ''
  with-arith-overflow: true
  horn-unify-assumes: true
# do not instrument library functions with memory assertions
  # no-fat-fns: 'bcmp,memcpy,assert_bytes_match,ensure_linked_list_is_allocated,sea_aws_linked_list_is_valid'
  horn-gsa: true
# context-sensitive type-aware alias analysis 
  dsa: sea-cs-t
# weak support for function pointers. sea-dsa is better but less stable
  devirt-functions: 'sea-dsa'
# bit-precise memory-precise operational semantics
  bmc: opsem
  horn-vcgen-use-ite: ''
# ignore control flow
  horn-vcgen-only-dataflow: true
# reduce by data dependence
  horn-bmc-coi: true
# static allocator supports symbolic allocation size
  sea-opsem-allocator: static
# stack allocation from a symbolic starting point
  horn-explicit-sp0: false
# lambdas for memory
  horn-bv2-lambdas: false
# use z3 simplifier during vcgen
  horn-bv2-simplify: true
# wide memory manager to track pointer sizes
  horn-bv2-extra-widemem: ''
# intermediate results in human readable form for debugging
  '-S': ''
# keep intermediate results for debugging 
  keep-temps: ''
  temp-dir: /tmp/verify-c-common
# time and result stats
  horn-stats: true
# produce counterexample harness
  cex: /tmp/h.ll
# printable counterexample log
  log: cex
# number of words to unroll symbolic memcpy for array-based memory representation
# should be at least MAX_BUFFER_SIZE
  horn-array-sym-memcpy-unroll-count: 10
# print memory state as a table
# XXX still flaky, sometimes only the last byte can be trusted
  horn-bmc-hexdump: true
  bound: 10
```
